version: "3.8"
services:
  database:
    image: mariadb
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST : "${DB_HOST}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - ~/stageHand_php/mysql:/var/lib/mariadb/data
    ports:
      - '${DB_PORT}:${DB_PORT}'
  php-apache:
    container_name: php-apache
    build:
      context: ./php
    ports:
        - '8080:80'
    volumes:
      - ~/stageHand_php/src:/var/www/laravel_docker
      - ~/stageHand_php/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database
